export interface DataManifest {
  version: string;
  builtAt: string;
  totalRows: number;
  shards: DataShardMeta[];
  dictionaries: DataDictionaries;
  /** Flat service-type → category map, generated by the Python build. Single source of truth. */
  categoryMap: Record<string, string>;
  defaults: { windowDays: number };
  /** Response-time percentiles per service type (citywide and per ward). */
  estimates?: EstimateRow[];
}

export interface DataShardMeta {
  id: string;
  file: string;
  rollupFile: string;
  rowCount: number;
  minDate: number;
  maxDate: number;
}

export interface DataDictionaries {
  serviceTypes: string[];
  agencies: string[];
  statuses: string[];
  wards: string[];
  categories: string[];
  dayOfWeek: string[];
  ageBuckets: string[];
  zipcodes: string[];
  cities: string[];
  states: string[];
  serviceTypeCodes: string[];
  serviceCodes: string[];
  priorities: string[];
}

export interface CompactRow {
  id: string;
  a: number;
  r: number | null;
  dd: number | null;
  st: number;
  ag: number | null;
  ss: number;
  w: number;
  c: number;
  lat: number | null;
  lng: number | null;
  io: number;
  ic: number;
  ad: number;
  rd: number | null;
  h: number;
  dow: number;
  wk: number;
  ab: number;
  addr: string | null;
  det: string | null;
  zip: number | null;
  city: number | null;
  state: number | null;
  sc: number | null;
  pri: number | null;
  stc: number | null;
}

export interface ShardFile {
  month: string;
  rows: CompactRow[];
}

export interface SlaRollupRow {
  serviceType: number;
  category: number;
  agency: number | null;
  sla_days: number;
  total: number;
  closed: number;
  met_sla_count: number;
  missed_sla_count: number;
  open_past_sla_count: number;
  median_resolution: number;
  p99_resolution: number;
  pct_resolved: number;
  pct_met_sla: number;
}

export interface ExplorerRollup {
  categoryBreakdown: Array<{ c: number; open: number; resolved: number }>;
  dayOfWeek: Array<{ dow: number; c: number; n: number }>;
  wardVolume: Array<{ w: number; open: number; resolved: number }>;
  typeCounts: Array<{ st: number; open: number; resolved: number }>;
  weeklyVolume: Array<{ wk: number; c: number; n: number }>;
}

export interface RollupFile {
  month: string;
  sla: SlaRollupRow[];
  explorer: ExplorerRollup;
}

export interface EstimateRow {
  st: number;
  w: number | null;
  n: number;
  p25: number;
  p50: number;
  p75: number;
  p90: number;
  p95?: number;
  sla_days: number;
  pct_met_sla: number;
}

export type DateRangePreset = '90d' | 'full';

export interface LoadProgress {
  loaded: number;
  total: number;
  currentShard: string;
}

export interface DashboardData {
  manifest: DataManifest;
  rows: import('../lib/dataProcessing').ProcessedRequest[];
  loadedShards: string[];
  monthlyRollups: RollupFile[];
  rollups: import('../lib/rollups').MergedRollups;
}
